#!/usr/bin/env python3
# Auto-generated by AuthRecorder Pro v2.0.0
# Cookie-based authentication script

import json
import requests

def load_cookies_and_test():
    """Load cookies and test authentication"""
    session = requests.Session()
    
    with open("cookies.json", "r", encoding="utf-8") as f:
        cookies = json.load(f)
    
    for cookie in cookies:
        session.cookies.set(
            cookie["name"], 
            cookie["value"], 
            domain=cookie.get("domain"), 
            path=cookie.get("path")
        )
    
    print("Cookies loaded. Testing authentication...")
    
    # Test with the first captured URL
    test_url = "https://httpbin.org/forms/post"
    r = session.get(test_url)
    print("Status:", r.status_code)
    print("Response preview:", r.text[:400])
    
    return session

if __name__ == "__main__":
    session = load_cookies_and_test()
