#!/usr/bin/env python3
# Auto-generated by AuthRecorder Pro v2.0.0
# Playwright cookie test script

from playwright.sync_api import sync_playwright
import json

def test_with_playwright():
    """Test authentication using Playwright with cookies"""
    with open("cookies.json", "r", encoding="utf-8") as f:
        cookies = json.load(f)
    
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context()
        context.add_cookies(cookies)
        page = context.new_page()
        
        test_url = "https://httpbin.org/forms/post"
        page.goto(test_url, wait_until="networkidle")
        print("Page title:", page.title())
        
        # Keep browser open for inspection
        input("Press Enter to close browser...")
        browser.close()

if __name__ == "__main__":
    test_with_playwright()
